---
- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=~/bin --filename=composer
  args: 
    creates: ~/bin/composer
- name: Setup oauth key for composer
  composer:
    command: config
    arguments: "--global github-oauth.github.com {{ composer_github_oauth }}"
